-- CREATE TABLE profiles(
--   id VARCHAR(255) NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     email VARCHAR(255) NOT NULL,
--     PRIMARY KEY (id)
-- )

-- ALTER TABLE profiles
-- DROP COLUMN specialty
-- ALTER TABLE profiles
-- DROP COLUMN isLicensed
